version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"  # Frontend port
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - RUSTUP_TOOLCHAIN=nightly
    command: trunk serve --address 0.0.0.0 --port 3000

volumes:
  cargo-cache:
  target-cache:
  node-modules: 